services:
  mongodb:
      image: mongo:latest
      container_name: mongodb
      restart: unless-stopped
      ports: 
        - "27017:27017"
      environment:
       - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
       - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PWD}
       - MONGO_INITDB_DATABASE=iot_db
      volumes:
        - mongo-data:/data/db
        - mongo-config:/data/configdb
        - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
volumes:
  mongo-data:
    driver: local
  mongo-config:
    driver: local